# Generated by Django 5.2.5 on 2025-08-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('duracion', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=100)),
                ('cupos', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paterno', models.CharField(max_length=255)),
                ('materno', models.CharField(max_length=255)),
                ('nombre_p', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=12)),
                ('rol', models.CharField(choices=[('est', 'Estudiante'), ('prof', 'Profesor')], max_length=4)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
